### ISSUE TITLE
When tag contracts docs are not pushed to `nvm-docs`

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/contracts#353] opened 2022-07-22 11:16 UTC

**Comment by jcortejoso** [comment] 2022-07-29 13:11
There were/are a couple of issues with current action setup:

- Error was caused by `[widdershins](https://github.com/Mermade/widdershins)` trying to convert from json to markdown the doc's file _category_.json. I have removed the `widdershins` execution as it seems it is not used/needed any longer, but if it is needed for any project we can exclude that file from `widdershins` execution.
- Workspace is not shared between different jobs inside the same workflow. That means that the docs generated during the `[build-doc](https://github.com/nevermined-io/contracts/blob/master/.github/workflows/push-to-docs.yml#L10)` job are not shared with `push-to-docs` job, and then *it requires that the documentation output to be committed to the repository* as it is now. There is not an easy workaround for sharing state between jobs, you can use artifacts and cache but it seems a bit complex when the input is unknown. Another ad-hoc solution is developing a custom action for some of the work done in the `push-to-docs` shared workflow.

**Closed** 2022-10-17 06:46 UTC
Labels: bug, documentation
